package enums;

public enum Operacion {
    SUCURSAL_ALTA,
    SUCURSAL_BAJA,
    SUCURSAL_MODIFICACION,

    USUARIO_ALTA,
    USUARIO_BAJA,
    USUARIO_MODIFICACION,

    PETICION_ALTA,
    PETICION_BAJA,
    PETICION_MODIFICACION,

    PRACTICA_ALTA,
    PRACTICA_BAJA,
    PRACTICA_MODIFICACION,

    RESULTADO_ALTA,
    RESULTADO_BAJA,
    RESULTADO_MODIFICACION,

    PACIENTE_ALTA,
    PACIENTE_BAJA,
    PACIENTE_MODIFICACION,

    MUESTRA_PROCESAR
}
